# Generated by Django 3.1.4 on 2021-01-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleaverequest',
            name='Leave_Status',
            field=models.CharField(choices=[('Pending_Status', 'Pending'), ('Approved_Status', 'Approved'), ('Declined_Status', 'Declined'), ('Cancelled_Status', 'Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='empleaverequest',
            name='Leave_Type',
            field=models.CharField(choices=[('Personal_Leave', 'Personal'), ('Annual_Leave', 'Annual'), ('Pregnancy_Disability_Leave', 'PDL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Designation',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Worktype',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Probationary', 'Probationary'), ('Limited_term', 'Limited-term'), ('Temporary', 'Temporary')], max_length=15),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='Leave_Type',
            field=models.CharField(choices=[('Personal_Leave', 'Personal'), ('Annual_Leave', 'Annual'), ('Pregnancy_Disability_Leave', 'PDL')], max_length=30),
        ),
    ]
