# Generated by Django 3.1.4 on 2021-01-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_Manager', '0002_auto_20210108_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Month', models.CharField(max_length=10)),
                ('Day', models.CharField(max_length=10)),
                ('Occasion', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=30)),
                ('Type', models.CharField(choices=[('Mandatory', 'Mandatory'), ('Optional', 'Optional')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='empleaverequest',
            name='Leave_Type',
            field=models.CharField(choices=[('Sick_Leave', 'Sick'), ('Annual_Leave', 'Annual'), ('Pregnancy_Disability_Leave', 'PDL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='Leave_Type',
            field=models.CharField(choices=[('Sick_Leave', 'Sick'), ('Annual_Leave', 'Annual'), ('Pregnancy_Disability_Leave', 'PDL')], max_length=30),
        ),
    ]
